[tool.poetry]
name = "schedly"
version = "0.1.0"
description = "Agent for appointment management"
authors = ["Ignacio Sánchez <nachosanchezh@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = {extras = ["email"], version = "^2.10.4"}
langchain = "^0.3.14"
langchain-core = "^0.3.29"
langchain-openai = "^0.2.14"
langgraph = "^0.2.60"
sqlalchemy = "^2.0.36"
streamlit = "^1.41.1"
psycopg = "^3.2.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
faker = "^33.3.0"
debugpy = "^1.8.11"
black = "^24.10.0"
mypy = "^1.14.1"
mypy-extensions = "^1.0.0"
pre-commit = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
