"""Add TelegramBots tables

Revision ID: 4c26302cc08a
Revises: d394dbbe5710
Create Date: 2025-06-08 09:39:40.668070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c26302cc08a"
down_revision: Union[str, None] = "d394dbbe5710"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_bots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_username", sa.String(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_username"),
        sa.UniqueConstraint("token"),
    )
    op.drop_constraint("customers_email_key", "customers", type_="unique")
    op.drop_constraint("customers_phone_key", "customers", type_="unique")
    op.drop_index("ix_customers_telegram_name", table_name="customers")
    op.create_index(
        op.f("ix_customers_telegram_name"),
        "customers",
        ["telegram_name"],
        unique=False,
    )
    op.add_column(
        "employees",
        sa.Column("google_calendar_id", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "google_calendar_id")
    op.drop_index(op.f("ix_customers_telegram_name"), table_name="customers")
    op.create_index(
        "ix_customers_telegram_name",
        "customers",
        ["telegram_name"],
        unique=True,
    )
    op.create_unique_constraint("customers_phone_key", "customers", ["phone"])
    op.create_unique_constraint("customers_email_key", "customers", ["email"])
    op.drop_table("telegram_bots")
    # ### end Alembic commands ###
