"""Add TelegramBots tables

Revision ID: 7ea4fb80b321
Revises: 4c26302cc08a
Create Date: 2025-06-08 09:43:08.986249

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ea4fb80b321"
down_revision: Union[str, None] = "4c26302cc08a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_bots",
        sa.Column("telegram_id", sa.Integer(), nullable=True),
    )
    op.create_unique_constraint(None, "telegram_bots", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "telegram_bots", type_="unique")
    op.drop_column("telegram_bots", "telegram_id")
    # ### end Alembic commands ###
