"""Modify relationship between appointment, services and employees

Revision ID: ffa742df6651
Revises: a997c93995f1
Create Date: 2025-06-09 21:01:10.848830

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffa742df6651"
down_revision: Union[str, None] = "a997c93995f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 2: Add new auto-incrementing ID column as PK
    op.add_column(
        "employee_services",
        sa.Column(
            "id",
            sa.Integer(),
            primary_key=True,
            autoincrement=True,
            nullable=False,
        ),
    )
    op.create_primary_key("employee_services_pkey", "employee_services", ["id"])

    # Step 3: Optionally enforce uniqueness on the (employee_id, service_id) pair
    op.create_unique_constraint(
        "uq_employee_service_pair",
        "employee_services",
        ["employee_id", "service_id"],
    )

    # Step 4: Add foreign key in appointments
    op.add_column(
        "appointments",
        sa.Column("employee_service_id", sa.Integer(), nullable=False),
    )

    # Step 5: Drop the old foreign keys
    op.drop_constraint(
        "appointments_employee_id_fkey",
        "appointments",
        type_="foreignkey",
    )
    op.drop_constraint(
        "appointments_service_id_fkey",
        "appointments",
        type_="foreignkey",
    )

    # Step 6: Drop the old columns
    op.drop_column("appointments", "employee_id")
    op.drop_column("appointments", "service_id")

    # Step 7: Add new foreign key
    op.create_foreign_key(
        None,
        "appointments",
        "employee_services",
        ["employee_service_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee_services", "id")
    op.add_column(
        "appointments",
        sa.Column("service_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "appointments",
        sa.Column("employee_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "appointments", type_="foreignkey")
    op.create_foreign_key(
        "appointments_service_id_fkey",
        "appointments",
        "services",
        ["service_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "appointments_employee_id_fkey",
        "appointments",
        "employees",
        ["employee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("appointments", "employee_service_id")
    # ### end Alembic commands ###
