"""Add calendar ID to appointments

Revision ID: a997c93995f1
Revises: 9fa48b38d3f9
Create Date: 2025-06-08 11:24:48.058495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a997c93995f1"
down_revision: Union[str, None] = "9fa48b38d3f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointments",
        sa.Column("google_calendar_id", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointments", "google_calendar_id")
    # ### end Alembic commands ###
