"""Modify business credentials storage

Revision ID: 6679f76b2026
Revises: 6aab679fa209
Create Date: 2025-06-07 12:49:20.520347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6679f76b2026"
down_revision: Union[str, None] = "6aab679fa209"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("business", sa.Column("google_credentials", sa.JSON(), nullable=True))
    op.drop_column("business", "access_token")
    op.drop_column("business", "refresh_token")
    op.drop_column("business", "google_user_id")
    op.add_column(
        "employee_services",
        sa.Column("employee_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "stylist_services_stylist_id_fkey",
        "employee_services",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "employee_services",
        "employees",
        ["employee_id"],
        ["id"],
    )
    op.drop_column("employee_services", "stylist_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee_services",
        sa.Column("stylist_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "employee_services", type_="foreignkey")
    op.create_foreign_key(
        "stylist_services_stylist_id_fkey",
        "employee_services",
        "employees",
        ["stylist_id"],
        ["id"],
    )
    op.drop_column("employee_services", "employee_id")
    op.add_column(
        "business",
        sa.Column("google_user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "business",
        sa.Column("refresh_token", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "business",
        sa.Column("access_token", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("business", "google_credentials")
    # ### end Alembic commands ###
