"""Add multitenant, a tenant per business

Revision ID: d394dbbe5710
Revises: 6679f76b2026
Create Date: 2025-06-07 20:34:31.265667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d394dbbe5710"
down_revision: Union[str, None] = "6679f76b2026"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "appointments_employee_id_fkey",
        "appointments",
        type_="foreignkey",
    )
    op.drop_constraint(
        "appointments_service_id_fkey",
        "appointments",
        type_="foreignkey",
    )
    op.drop_constraint(
        "appointments_customer_id_fkey",
        "appointments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "appointments",
        "employees",
        ["employee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "appointments",
        "services",
        ["service_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "appointments",
        "customers",
        ["customer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("customers", sa.Column("business_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None,
        "customers",
        "business",
        ["business_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "stylist_services_service_id_fkey",
        "employee_services",
        type_="foreignkey",
    )
    op.drop_constraint(
        "employee_services_employee_id_fkey",
        "employee_services",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "employee_services",
        "services",
        ["service_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "employee_services",
        "employees",
        ["employee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("employees_business_id_fkey", "employees", type_="foreignkey")
    op.create_foreign_key(
        None,
        "employees",
        "business",
        ["business_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("services", sa.Column("business_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None,
        "services",
        "business",
        ["business_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "work_schedules_employee_id_fkey",
        "work_schedules",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "work_schedules",
        "employees",
        ["employee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "work_schedules", type_="foreignkey")
    op.create_foreign_key(
        "work_schedules_employee_id_fkey",
        "work_schedules",
        "employees",
        ["employee_id"],
        ["id"],
    )
    op.drop_constraint(None, "services", type_="foreignkey")
    op.drop_column("services", "business_id")
    op.drop_constraint(None, "employees", type_="foreignkey")
    op.create_foreign_key(
        "employees_business_id_fkey",
        "employees",
        "business",
        ["business_id"],
        ["id"],
    )
    op.drop_constraint(None, "employee_services", type_="foreignkey")
    op.drop_constraint(None, "employee_services", type_="foreignkey")
    op.create_foreign_key(
        "employee_services_employee_id_fkey",
        "employee_services",
        "employees",
        ["employee_id"],
        ["id"],
    )
    op.create_foreign_key(
        "stylist_services_service_id_fkey",
        "employee_services",
        "services",
        ["service_id"],
        ["id"],
    )
    op.drop_constraint(None, "customers", type_="foreignkey")
    op.drop_column("customers", "business_id")
    op.drop_constraint(None, "appointments", type_="foreignkey")
    op.drop_constraint(None, "appointments", type_="foreignkey")
    op.drop_constraint(None, "appointments", type_="foreignkey")
    op.create_foreign_key(
        "appointments_customer_id_fkey",
        "appointments",
        "customers",
        ["customer_id"],
        ["id"],
    )
    op.create_foreign_key(
        "appointments_service_id_fkey",
        "appointments",
        "services",
        ["service_id"],
        ["id"],
    )
    op.create_foreign_key(
        "appointments_employee_id_fkey",
        "appointments",
        "employees",
        ["employee_id"],
        ["id"],
    )
    # ### end Alembic commands ###
