"""Modify bot id data type

Revision ID: ada8d1411e31
Revises: 4347690ab409
Create Date: 2025-06-08 09:49:06.101648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ada8d1411e31"
down_revision: Union[str, None] = "4347690ab409"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "telegram_bots",
        "business_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.drop_constraint("telegram_bots_telegram_id_key", "telegram_bots", type_="unique")
    op.drop_constraint(
        "telegram_bots_telegram_username_key",
        "telegram_bots",
        type_="unique",
    )
    op.create_index(
        op.f("ix_telegram_bots_telegram_username"),
        "telegram_bots",
        ["telegram_username"],
        unique=True,
    )
    op.drop_constraint(
        "telegram_bots_business_id_fkey",
        "telegram_bots",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "telegram_bots",
        "business",
        ["business_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("telegram_bots", "telegram_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_bots",
        sa.Column("telegram_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "telegram_bots", type_="foreignkey")
    op.create_foreign_key(
        "telegram_bots_business_id_fkey",
        "telegram_bots",
        "business",
        ["business_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_telegram_bots_telegram_username"),
        table_name="telegram_bots",
    )
    op.create_unique_constraint(
        "telegram_bots_telegram_username_key",
        "telegram_bots",
        ["telegram_username"],
    )
    op.create_unique_constraint(
        "telegram_bots_telegram_id_key",
        "telegram_bots",
        ["telegram_id"],
    )
    op.alter_column(
        "telegram_bots",
        "business_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
