"""update customer

Revision ID: 82c123a2de67
Revises: 525662c167fc
Create Date: 2025-05-04 10:34:58.424429

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "82c123a2de67"
down_revision: Union[str, None] = "525662c167fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customers",
        "name",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "customers",
        "phone",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_index("ix_customers_phone", table_name="customers")
    op.create_unique_constraint(None, "customers", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "customers", type_="unique")
    op.create_index("ix_customers_phone", "customers", ["phone"], unique=True)
    op.alter_column(
        "customers",
        "phone",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "customers",
        "name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
