"""Add calendar ID to employees

Revision ID: 9fa48b38d3f9
Revises: ada8d1411e31
Create Date: 2025-06-08 09:57:58.246038

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fa48b38d3f9"
down_revision: Union[str, None] = "ada8d1411e31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "google_calendar_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "employees", ["google_calendar_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employees", type_="unique")
    op.alter_column(
        "employees",
        "google_calendar_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
