"""Add whatsapp bot

Revision ID: 6ea7c46194f1
Revises: ffa742df6651
Create Date: 2025-07-06 22:06:23.043515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ea7c46194f1"
down_revision: Union[str, None] = "ffa742df6651"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whatsapp_bots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("waba_id", sa.String(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        op.f("ix_whatsapp_bots_waba_id"),
        "whatsapp_bots",
        ["waba_id"],
        unique=True,
    )
    op.add_column("customers", sa.Column("whatsapp_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_customers_whatsapp_id"),
        "customers",
        ["whatsapp_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customers_whatsapp_id"), table_name="customers")
    op.drop_column("customers", "whatsapp_id")
    op.drop_index(op.f("ix_whatsapp_bots_waba_id"), table_name="whatsapp_bots")
    op.drop_table("whatsapp_bots")
    # ### end Alembic commands ###
